baseUrl:      https://tikerlade.github.io/
theme:        "PaperMod"
buildDrafts:  false
displayFullLangName: true

params: 
  assets:
      disableHLJS: true
      favicon: "/assets/favicon.ico"

languages:
  en:
    title:        Ivan Kuznetsov
    languageName: ":gb:"
    contentDir:   content/en
    displayFullLangName: true
    weight: 1

    menu:
      main:
        - identifier: archive
          name: Archive
          url: /en/archive/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: sports
          name: Sports
          url: /sports/
          weight: 40

    params:
      env:              production
      ShowBreadCrumbs:  true
      defaultTheme:     auto # to switch between dark or light according to browser theme
      homeInfoParams:
        Title: Welcome 🤗
        Content: This is the place where **Ivan Kuznetsov** (me) will share things that I am passionate about. It could be Python / ML stuff, sports, ideas or achievements. I will try to tell about it in an interesting way (sure, with images)!

      socialIcons:
        - name:   github
          url:    "https://github.com/tikerlade"
        - name:   linkedin
          url:    "https://www.linkedin.com/in/kuznetsov-ivan/"

      assets:
          favicon: "/favicon.ico"
          favicon16x16:  "/favicon-16x16.png"
          favicon32x32:  "/favicon-32x32.png"
          apple_touch_icon:  "/apple-touch-icon.png"
          safari_pinned_tab:  "/safari-pinned-tab.svg"

  ru:
    title:        Иван Кузнецов
    languageName: ":ru:"
    contentDir: content/ru
    displayFullLangName: true
    weight: 2
    menu:
      main:
        - identifier: archive
          name: Архив
          url: /ru/archive/
          weight: 1
        - identifier: tags
          name: Теги
          url: /tags/
          weight: 2
        - identifier: sports
          name: Спорт
          url: /sports/
          weight: 3

    params:
      env:              production
      ShowBreadCrumbs:  true
      defaultTheme:     auto # to switch between dark or light according to browser theme
      homeInfoParams:
        Title: Привет 🤗
        Content: "Это уголок, где **Иван Кузнецов** (то бишь я) записываю вещи, относительно которых я не безразличен. Тут может быть про Python / ML, Спорт, мои идеи или достижения. Стараюсь писать интересно (и обязательно с картинками)."

      socialIcons:
        - name:   github
          url:    "https://github.com/tikerlade"
        - name:   linkedin
          url:    "https://www.linkedin.com/in/kuznetsov-ivan/"

      assets:
          favicon: "/favicon.ico"
          favicon16x16:  "/favicon-16x16.png"
          favicon32x32:  "/favicon-32x32.png"
          apple_touch_icon:  "/apple-touch-icon.png"
          safari_pinned_tab:  "/safari-pinned-tab.svg"
