baseUrl:      https://tikerlade.github.io/
languageCode: en-us
title:        Ivan Kuznetsov
theme:        "PaperMod"
buildDrafts:  true

params:
  env:              production
  ShowBreadCrumbs:  true
  defaultTheme:     auto # to switch between dark or light according to browser theme
  homeInfoParams:
    Title: Welcome 🤗
    Content: This is the place where **Ivan Kuznetsov** (me) will share things that I am passionate about. It could be Python / ML stuff, sports, ideas or achievements. I will try to tell about it in an interesting way (sure, with images)!

  socialIcons:
    - name:   github
      url:    "https://github.com/tikerlade"
    - name:   linkedin
      url:    "https://www.linkedin.com/in/kuznetsov-ivan/"
menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30