baseUrl:      https://tikerlade.github.io/
theme:        "PaperMod"
buildDrafts:  false
displayFullLangName: true

languages:
  en:
    title:        Ivan Kuznetsov
    languageName: ":gb:"
    contentDir:   content/en
    displayFullLangName: true
    env: production
    weight: 1
    enableEmoji: true

    menu:
      main:
        - identifier: blog
          name: Blog
          url: blog/
          weight: 10
        - identifier: edu
          name: Education
          url: education/
          weight: 40
        - identifier: careers
          name: Careers
          url: careers/
          weight: 50
        - identifier: sports
          name: Sports
          url: sports/
          weight: 60
        - identifier: tags
          name: Tags
          url: tags/
          weight: 70

    params:
      enableEmoji: true
      env:              production
      ShowBreadCrumbs:  true
      defaultTheme:     auto # to switch between dark or light according to browser theme
      homeInfoParams:
        Title: Welcome 🤗
        Content: This is the place where **Ivan Kuznetsov** (me) will share things that I am passionate about. It could be Python / ML stuff, sports, ideas or achievements. I will try to tell about it in an interesting way (sure, with images)!
      mainSections:
        - blog

      socialIcons:
        - name:   github
          url:    "https://github.com/tikerlade"
        - name:   linkedin
          url:    "https://www.linkedin.com/in/kuznetsov-ivan/"
        - name:   goodreads
          url:    "https://www.goodreads.com/user/show/128771516-ivan"
      assets:
          favicon: "/favicon.ico"
          favicon16x16:  "/favicon-16x16.png"
          favicon32x32:  "/favicon-32x32.png"
          apple_touch_icon:  "/apple-touch-icon.png"
          safari_pinned_tab:  "/safari-pinned-tab.svg"

  ru:
    title:        Иван Кузнецов
    languageName: ":ru:"
    contentDir: content/ru
    displayFullLangName: true
    weight: 2
    menu:
      main:
        - identifier: blog
          name: Блог
          url: blog/
          weight: 1
        - identifier: edu
          name: Образование
          url: education/
          weight: 4
        - identifier: careers
          name: Карьера
          url: careers/
          weight: 5
        - identifier: sports
          name: Спорт
          url: sports/
          weight: 6
        - identifier: tags
          name: Теги
          url: tags/
          weight: 8

    params:
      env:              production
      ShowBreadCrumbs:  true
      defaultTheme:     auto # to switch between dark or light according to browser theme
      homeInfoParams:
        Title: Привет 🤗
        Content: "Это уголок, где **Иван Кузнецов** (то бишь я) записываю вещи, относительно которых я не безразличен. Тут может быть про Python / ML, Спорт, мои идеи или достижения. Стараюсь писать интересно (и обязательно с картинками)."
      mainSections:
        - blog

      socialIcons:
        - name:   github
          url:    "https://github.com/tikerlade"
        - name:   linkedin
          url:    "https://www.linkedin.com/in/kuznetsov-ivan/"
        - name:   goodreads
          url:    "https://www.goodreads.com/user/show/128771516-ivan"

      assets:
          favicon: "/favicon.ico"
          favicon16x16:  "/favicon-16x16.png"
          favicon32x32:  "/favicon-32x32.png"
          apple_touch_icon:  "/apple-touch-icon.png"
          safari_pinned_tab:  "/safari-pinned-tab.svg"
